---
name: Go
on: [push]
jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.5
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
      - name: build application
        run: make build-sym

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: tmp
        run: ls -lah build


      #- name: Deploy static site to S3 bucket
      #  run: aws s3 cp out s3://cosmos-symbiotic-fi  --acl public-read
